version: '3.8'
services:

  gateway:
    build: gateway
    image: shareit_gateway_image
    container_name: shareit_gateway_container
    ports:
      - "8080:8080"
    depends_on:
    - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: shareit_server_image
    container_name: shareit_server_container
    ports:
      - "9090:9090"
    depends_on:
    - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareitdatabase
      - SPRING_DATASOURCE_USERNAME=shareit_user
      - SPRING_DATASOURCE_PASSWORD=shareituserpass


  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: shareit_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareitdatabase
      - POSTGRES_USER=shareit_user
      - POSTGRES_PASSWORD=shareituserpass